// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RupeshPathak

//@version=4
strategy("My Strategy", overlay=true, margin_long=10000, margin_short=10000,initial_capital=10000000000000000,max_bars_back= 5000)

start = input(0.02)
increment = input(0.02)
maximum = input(0.2, "Max Value")
out = sar(start, increment, maximum)
plot(out, "ParabolicSAR", style=plot.style_cross, color=#2962FF)
dir = out < close ? 1 : -1
buySignal = dir == 1 and dir[1] == -1
sellSignal = dir == -1 and dir[1] == 1
changeCond = dir != dir[1]



length = input(20, minval=1)
src = input(hlc3, title="Source")
ma = sma(src, length)
cci = (src - ma) / (0.015 * dev(src, length))
plot(cci, "CCI", color=#2962FF)

buySignalCCI = cci < 100
sellSignalCCI = cci > -100 

smoothK = input(3, "K", minval=1)
smoothD = input(3, "D", minval=1)
lengthRSI = input(14, "RSI Length", minval=1)
lengthStoch = input(14, "Stochastic Length", minval=1)
src1 = input(close, title="RSI Source")
rsi1 = rsi(src1, lengthRSI)
k = sma(stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = sma(k, smoothD)
plot(k, "K", color=#2962FF)
plot(d, "D", color=#FF6D00)
h0 = hline(80, "Upper Band", color=#787B86)
h1 = hline(20, "Lower Band", color=#787B86)
fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")

buySignalSRSI = k < 80 and d < 80
sellSignalSRSI =  k > 20 and d > 20

heikenBUY = open < close
heikenSELL = open > close

if (buySignal and buySignalSRSI and buySignalCCI and heikenBUY )
    strategy.entry("My Long Entry Id", strategy.long,qty = 1)

if (sellSignal and sellSignalCCI and sellSignalSRSI and heikenSELL )
    strategy.entry("My Short Entry Id", strategy.short, qty = 1)
